version: "3.9"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
  swagger-ui:
      ports:
          - '80:8080'
      environment:
          - SWAGGER_JSON=/schema.yml
      volumes:
          - '${PWD}/messengerapi/api-docs/swagger.yml:/schema.yml'
      image: swaggerapi/swagger-ui
